[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#7777aa"
foreground = "#1d1f21"

[font]
size = 9

[font.normal]
family = "Noto Sans Mono CJK SC"
[window]
opacity = 0.8
